export const USER_ACTION = {
  FETCH: "USER_FETCH",
  CREATE: "USER_CREATE",
  DELETE: "USER_DELETE",
  UPDATE: "USER_UPDATE",
  SHOW: "USER_SHOW",
  AUTH: "USER_AUTH"
};

export const POST_ACTION = {
  FETCH: "POST_FETCH",
  CREATE: "POST_CREATE",
  DELETE: "POST_DELETE",
  UPDATE: "POST_UPDATE",
  SHOW: "POST_SHOW"
};

export const ERROR_HANDLER = {
  ADD: "ERROR_ADD",
  REMOVE: "ERROR_REMOVE"
};
